### GET POSTS
GET http://localhost:3000/api/posts


### CREATE POST
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title" : "Title example",
    "content" : "This is the content"
}